### PR TITLE
56 generate grayscale and rgb histograms

### PR DESCRIPTION
**Pull request by cguz**
George, check the examples in the folder:

- results\spacecraft\images\AE\FPN-50\Earth\images\

and the result in the folder:

- results\spacecraft\images\AE\FPN-50\Earth\figures\

Moved the plot_histogram.py to:

- results\

### CODE REVIEW

**Comment by georgeslabreche** [comment]
1. Let's remove these sample images:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/spacecraft/images/AE/FPN-50/Earth/images

We already defined a sample image we consistently use everywhere and introducing a new one is confusing and unnecessary.

2. Are these the plots for the new samples I refer to in point 1? If so then remove them. See point 3 on what we need.
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/spacecraft/images/AE/FPN-50/Earth/figures

3. We want two sets of plots for the two WGAN spacecraft results and one set of plots for the WGAN flatsat sample. Here is the latter, which I was expecting to be regenerated by your new script but they haven't changed:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/flatsat/wgan_fpn50_p0-8_01/figures

4. Remember that for the Channels plots to look good in the paper we need their titles to be on the upper right hand corner of the plots. So instead of setting a title we probably have to just set a text label.

**Comment by cguz** [comment]
Hi Goerges, 

Could you please clarify the point (3.) ?

image

When you said "two WGAN spacecraft results", you mean: a) AE/FPN-50/ and b) WGAN/FPN-50/?

Regarding point (1.), we have the sample.jpeg. 

- What is the real identifier of that image? 
- Where do we have the denoiser images by applying a) and b)?

**Comment by georgeslabreche** [comment]
@cguz I mean the two pictures processed with WGAN, they are both here:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/main/results%2Fspacecraft%2Fimages%2FWGAN%2FFPN-50%2FEarth

These are the same two pictures presented in the paper for the in-flight WGAN results.

**Comment by georgeslabreche** [comment]
@cguz I mean the two pictures processed with WGAN, they are both here:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/main/results%2Fspacecraft%2Fimages%2FWGAN%2FFPN-50%2FEarth

These are the same two pictures presented in the paper for the in-flight WGAN results.

**Comment by georgeslabreche** [comment]
@cguz all the results for the WGANs sample processing that was done on the flatsat are in the flatsat results folder, here:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/main/results%2Fflatsat%2Fwgan_fpn50_p0-8_01%2Fimages

**Comment by cguz** [comment]
> @cguz for "the two WGAN spacecraft results" I mean the two pictures processed with WGAN onboard the spacecraft, they are both here: https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/main/results%2Fspacecraft%2Fimages%2FWGAN%2FFPN-50%2FEarth
> 
> These are the same two pictures presented in the paper for the in-flight WGAN results.

Ok. Done. 

Now, the images and histograms are here: https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/spacecraft/images/WGAN_FPN50/Earth

And : 

https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/flatsat/wgan_fpn50_p0-8_01/figures

@georgeslabreche , could you please check that everything is correct?

**Comment by georgeslabreche** [comment]
1) Here you reorganized the results images into their own timestamp folders:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/spacecraft/images/WGAN_FPN50/Earth

But I believe that breaks the following metrics scripts:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/spacecraft/calculate_metrics.py

Can you make sure that the script still works? If not, then it's best to revert back to having all the images directly under `results/spacecraft/images/WGAN_FPN50/Earth` and then separating the figures into their own folder in `results/spacecraft/figures/WGAN/FPN-50/Earth`


2) Don't put the figures folder inside the images folder, it's confusing, let's keep the images folder just for the satellite images:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/tree/56-generate-grayscale-and-rgb-histogram-for-autoencoder/results/spacecraft/images/AE/FPN-50/Earth

Instead create another folder `results/spacecraft/figures/AE/FPN-50/Earth`

How come we only have one set of figures? We should either do it for none of the images or for all?

3) Let's be consistent in the the folder structure across AE and WGAN results. Sometimes it's `WGAN_FPN50`, sometimes its `AI/FPN-50`. Stick to the latter structure.

$) I deleted some unnecessary files so be sure to git pull.

**Comment by georgeslabreche** [comment]
@cguz, another issue: the y-axis scale needs to be the same for the original and the denoised RGB histograms.

**Pull request merged**
